# Generated by Django 5.1.3 on 2024-12-06 10:32
from datetime import datetime

from django.db import migrations

def populate_data(apps, schema_editor):

    Event = apps.get_model('events', 'Event')

    events = [
        (1, 'Tech Summit 2024', 'A gathering of tech enthusiasts to explore emerging technologies.',
         '2024-12-10 09:00:00', 'London, United Kingdom', 2, 'https://example.com/image1.jpg', 1, 1),
        (2, 'Art Gala', 'A showcase of contemporary art from local artists.', '2024-12-15 18:00:00', 'Paris, France', 2,
         'https://example.com/image2.jpg', 2, 2),
        (3, 'Music Fiesta', 'Enjoy live music performances from renowned bands.', '2025-01-20 19:30:00','New York, USA',
            2, 'https://example.com/image3.jpg', 3, 3),
        (4, 'Startup Pitch Night', 'Pitch your ideas to top investors and mentors.', '2025-03-05 14:00:00',
         'Berlin, Germany', 2, 'https://example.com/image4.jpg', 4, 4),
        (5, 'Gaming Championship', 'A gaming event for e-sports enthusiasts.', '2025-02-14 10:00:00', 'Tokyo, Japan', 2,
         'https://example.com/image5.jpg', 5, 5),
        (6, 'Community Meetup', 'Meet local professionals and expand your network.', '2025-01-12 17:00:00',
         'Toronto, Canada', 2, 'https://example.com/image6.jpg', 6, 1),
        (7, 'Health & Wellness Workshop', 'Explore ways to maintain mental and physical health.', '2025-03-17 11:00:00',
         'Sydney, Australia', 2, 'https://example.com/image7.jpg', 7, 2),
        (8, 'Food Fest', 'Indulge in delicious cuisines from around the world.', '2025-04-22 13:00:00', 'Rome, Italy', 2,
            'https://example.com/image8.jpg', 8, 3),
        (9, 'Book Fair 2025', 'Discover new books and meet your favorite authors.', '2025-05-10 10:00:00',
         'Buenos Aires, Argentina', 2, 'https://example.com/image9.jpg', 9, 4),
        (10, 'Education Expo', 'An event showcasing opportunities in education.', '2025-06-18 09:30:00',
         'London, United Kingdom', 2, 'https://example.com/image10.jpg', 10, 5),
        (11, 'AI Conference', 'Discuss advancements in artificial intelligence.', '2025-07-19 14:00:00',
         'San Francisco, USA', 2, 'https://example.com/image11.jpg', 11, 1),
        (12, 'Film Festival', 'Watch and celebrate movies from around the world.', '2025-08-23 16:00:00',
         'Cannes, France', 2, 'https://example.com/image12.jpg', 12, 2),
        (13, 'Car Expo', 'A display of the latest innovations in automobiles.', '2025-09-12 12:00:00','Munich, Germany',
            2, 'https://example.com/image13.jpg', 13, 3),
        (14, 'Science Fair', 'Showcase groundbreaking science projects.', '2025-10-06 10:30:00', 'Tokyo, Japan', 2,
         'https://example.com/image14.jpg', 14, 4),
        (15, 'Fashion Show', 'A runway event featuring new trends in fashion.', '2025-11-11 18:30:00', 'Milan, Italy',
         2, 'https://example.com/image15.jpg', 15, 5),
        (16, 'Tech Fair', 'Technology companies display the latest gadgets and software.', '2025-12-10 11:00:00',
         'Seoul, South Korea', 2, 'https://example.com/image16.jpg', 16, 6),
        (17, 'Historical Reenactment', 'Live-action representation of historical events.', '2026-01-15 15:00:00',
         'Athens, Greece', 2, 'https://example.com/image17.jpg', 17, 7),
        (18, 'Literature Fest', 'Interactive sessions with best-selling authors.', '2026-03-21 12:30:00',
         'Dublin, Ireland', 2, 'https://example.com/image18.jpg', 18, 8),
        (19, 'Start-Up Week', 'Week-long conference for entrepreneurs.', '2026-05-18 09:00:00', 'New York, USA', 2,
         'https://example.com/image19.jpg', 19, 9),
        (20, 'Coding Hackathon', 'Solve problems and build applications in a day.', '2026-07-09 10:00:00',
         'Berlin, Germany', 2, 'https://example.com/image20.jpg', 20, 10),
        (21, 'International Food Expo', 'Taste dishes from cultures around the world.', '2026-08-12 14:00:00',
         'Mexico City, Mexico', 2, 'https://example.com/image21.jpg', 21, 1),
        (22, 'Jazz Night', 'Enjoy a night of smooth jazz music.', '2026-09-22 20:00:00', 'New Orleans, USA', 2,
         'https://example.com/image22.jpg', 22, 2),
        (23, 'Summer Carnival', 'A fun-filled event with games, rides, and food.', '2026-10-07 10:00:00',
         'Rio de Janeiro, Brazil', 2, 'https://example.com/image23.jpg', 23, 3),
        (24, 'Startup Bootcamp', 'Workshops and seminars for aspiring entrepreneurs.', '2026-11-04 09:00:00',
         'London, United Kingdom', 2, 'https://example.com/image24.jpg', 24, 4),
        (25, 'Digital Marketing Summit', 'Learn the latest strategies in digital marketing.', '2026-12-15 11:30:00',
         'Los Angeles, USA', 2, 'https://example.com/image25.jpg', 25, 5),
        (26, 'Mobile App Expo', 'Showcasing the most innovative mobile apps.', '2027-01-25 10:00:00', 'Dubai, UAE', 1,
         'https://example.com/image26.jpg', 26, 6),
        (27, 'Green Living Expo', 'Learn about sustainable living practices.', '2027-02-18 13:00:00',
         'Vancouver, Canada', 2, 'https://example.com/image27.jpg', 27, 7),
        (28, 'Space Exploration Conference', 'Exploring the future of space travel and research.','2027-03-22 09:00:00',
            'Houston, USA', 2, 'https://example.com/image28.jpg', 28, 8),
        (29, 'Comic Con', 'Meet comic book creators and see exclusive releases.', '2027-04-14 14:00:00',
         'San Diego, USA', 2, 'https://example.com/image29.jpg', 29, 9),
        (30, 'Virtual Reality Expo', 'Experience the latest in virtual reality technology.', '2027-05-10 12:00:00',
         'Los Angeles, USA', 2, 'https://example.com/image30.jpg', 30, 10),
        (31, 'Blockchain Summit', 'Discover the potential of blockchain technology.', '2027-06-02 09:30:00',
         'Zurich, Switzerland', 2, 'https://example.com/image31.jpg', 31, 1),
        (32, 'Drone Racing Championship', 'Witness high-speed drone races.', '2027-07-20 15:00:00', 'Las Vegas, USA',
            2,'https://example.com/image32.jpg', 1, 2),
        (33, 'Luxury Car Show', 'See the latest luxury vehicles from top brands.', '2027-08-11 10:00:00',
         'Monaco, Monaco', 2, 'https://example.com/image33.jpg', 33, 3),
        (34, 'Tech Conference', 'Explore the latest in technology and innovation.', '2027-09-03 08:30:00',
         'Singapore, Singapore', 2, 'https://example.com/image34.jpgHere', 30, 5)
    ]
    for event in events:
        Event.objects.create(
            title=event[1],
            description=event[2],
            date=event[3],
            location=event[4],
            created_by_id=event[5],
            created_at=datetime.now(),
            updated_at=datetime.now(),
            image=event[6],
            venue_id=event[7],
            organizer_id=event[8]
        )

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_image'),
    ]

    operations = [ migrations.RunPython(populate_data)]
